services:
  minerugw-02:
    build:
      context: .
    container_name: mineru-gw-02
    ports:
      - "8988:80"
    volumes:
      - ./api:/minerugw/app:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      TZ: Asia/Shanghai
    command: ["/minerugw/app/start.sh"]
    restart: always
    networks:
      - default

networks:
  default:
    driver: bridge
