# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: update-base
on:
  push:
    tags:
      - "*released"
  workflow_dispatch:
jobs:
  pdf-test:
    runs-on: pdf
    timeout-minutes: 40

    steps:
      - name: update-base
        uses: actions/checkout@v4
      - name: start-update
        run: |
          echo "start test"
